export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGIN_RESET: 'LOGIN_RESET',
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
    CREATE_NEW_PASSWORD_REQUEST: 'CREATE_NEW_PASSWORD_REQUEST',
    CREATE_NEW_PASSWORD_SUCCESS: 'CREATE_NEW_PASSWORD_SUCCESS',
    CREATE_NEW_PASSWORD_FAILURE: 'CREATE_NEW_PASSWORD_FAILURE',
}

export const userConstants = {
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'ADD_USER_FAILURE',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
}

export const categoryConstants = {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
}

export const courseConstants = {
    GET_COURSE_DETAIL_REQUEST: 'GET_COURSE_DETAIL_REQUEST',
    GET_COURSE_DETAIL_SUCCESS: 'GET_COURSE_DETAIL_SUCCESS',
    GET_COURSE_DETAIL_FAILURE: 'GET_COURSE_DETAIL_FAILURE',
    GET_COURSES_REQUEST: 'GET_COURSES_REQUEST',
    GET_COURSES_SUCCESS: 'GET_COURSES_SUCCESS',
    GET_COURSES_FAILURE: 'GET_COURSES_FAILURE',
    ADD_COURSE_REQUEST: 'ADD_COURSE_REQUEST',
    ADD_COURSE_SUCCESS: 'ADD_COURSE_SUCCESS',
    ADD_COURSE_FAILURE: 'ADD_COURSE_FAILURE',
    UPDATE_COURSE_REQUEST: 'UPDATE_COURSE_REQUEST',
    UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
    UPDATE_COURSE_FAILURE: 'UPDATE_COURSE_FAILURE',
    DELETE_COURSE_REQUEST: 'DELETE_COURSE_REQUEST',
    DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
    DELETE_COURSE_FAILURE: 'DELETE_COURSE_FAILURE',
    SEND_REQUEST_TO_JOIN_COURSE_REQUEST: 'SEND_REQUEST_TO_JOIN_COURSE_REQUEST',
    SEND_REQUEST_TO_JOIN_COURSE_SUCCESS: 'SEND_REQUEST_TO_JOIN_COURSE_SUCCESS',
    SEND_REQUEST_TO_JOIN_COURSE_FAILURE: 'SEND_REQUEST_TO_JOIN_COURSE_FAILURE',
    JOIN_COURSE_REQUEST: 'JOIN_COURSE_REQUEST',
    JOIN_COURSE_SUCCESS: 'JOIN_COURSE_SUCCESS',
    JOIN_COURSE_FAILURE: 'JOIN_COURSE_FAILURE',
    UPLOAD_VIDEO_COURSE_REQUEST: 'UPLOAD_VIDEO_COURSE_REQUEST',
    UPLOAD_VIDEO_COURSE_SUCCESS: 'UPLOAD_VIDEO_COURSE_SUCCESS',
    UPLOAD_VIDEO_COURSE_FAILURE: 'UPLOAD_VIDEO_COURSE_FAILURE',
}

export const blogConstants = {
    GET_BLOG_DETAIL_REQUEST: 'GET_BLOG_DETAIL_REQUEST',
    GET_BLOG_DETAIL_SUCCESS: 'GET_BLOG_DETAIL_SUCCESS',
    GET_BLOG_DETAIL_FAILURE: 'GET_BLOG_DETAIL_FAILURE',
    GET_BLOGS_REQUEST: 'GET_BLOGS_REQUEST',
    GET_BLOGS_SUCCESS: 'GET_BLOGS_SUCCESS',
    GET_BLOGS_FAILURE: 'GET_BLOGS_FAILURE',
    ADD_BLOG_REQUEST: 'ADD_BLOG_REQUEST',
    ADD_BLOG_SUCCESS: 'ADD_BLOG_SUCCESS',
    ADD_BLOG_FAILURE: 'ADD_BLOG_FAILURE',
    UPDATE_BLOG_REQUEST: 'UPDATE_BLOG_REQUEST',
    UPDATE_BLOG_SUCCESS: 'UPDATE_BLOG_SUCCESS',
    UPDATE_BLOG_FAILURE: 'UPDATE_BLOG_FAILURE',
    DELETE_BLOG_REQUEST: 'DELETE_BLOG_REQUEST',
    DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
    DELETE_BLOG_FAILURE: 'DELETE_BLOG_FAILURE',
}

export const chatConstants = {
    GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',
    UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_FAILURE: 'UPLOAD_FILE_FAILURE',
    GET_MESSAGE_AFTER_SEND: 'GET_MESSAGE_AFTER_SEND',
}

export const activityConstants = {
    'GET_DETAIL_ACTIVITY_REQUEST': 'GET_DETAIL_ACTIVITY_REQUEST',
    'GET_DETAIL_ACTIVITY_SUCCESS': 'GET_DETAIL_ACTIVITY_SUCCESS',
    'GET_DETAIL_ACTIVITY_FAILURE': 'GET_DETAIL_ACTIVITY_FAILURE',
    'GET_LIST_ACTIVITY_REQUEST': 'GET_LIST_ACTIVITY_REQUEST',
    'GET_LIST_ACTIVITY_SUCCESS': 'GET_LIST_ACTIVITY_SUCCESS',
    'GET_LIST_ACTIVITY_FAILURE': 'GET_LIST_ACTIVITY_FAILURE',
    'CREATE_ACTIVITY_REQUEST': 'CREATE_ACTIVITY_REQUEST',
    'CREATE_ACTIVITY_SUCCESS': 'CREATE_ACTIVITY_SUCCESS',
    'CREATE_ACTIVITY_FAILURE': 'CREATE_ACTIVITY_FAILURE',
    'GRADE_ACTIVITY_REQUEST': 'GRADE_ACTIVITY_REQUEST',
    'GRADE_ACTIVITY_SUCCESS': 'GRADE_ACTIVITY_SUCCESS',
    'GRADE_ACTIVITY_FAILURE': 'GRADE_ACTIVITY_FAILURE',
    'UPLOAD_FILE_ACTIVITY_REQUEST': 'UPLOAD_FILE_ACTIVITY_REQUEST',
    'UPLOAD_FILE_ACTIVITY_SUCCESS': 'UPLOAD_FILE_ACTIVITY_SUCCESS',
    'UPLOAD_FILE_ACTIVITY_FAILURE': 'UPLOAD_FILE_ACTIVITY_FAILURE',
}

export const userCourseConstants = {
    'GET_USER_COURSE_INFO_REQUEST': 'GET_USER_COURSE_INFO_REQUEST',
    'GET_USER_COURSE_INFO_SUCCESS': 'GET_USER_COURSE_INFO_SUCCESS',
    'GET_USER_COURSE_INFO_FAILURE': 'GET_USER_COURSE_INFO_FAILURE',
}
